# Generated by Django 3.0.3 on 2020-03-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_item_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_price1',
            field=models.IntegerField(default='just checking'),
        ),
    ]
