# Generated by Django 3.0.3 on 2020-03-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_item_item_price1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_price1',
            field=models.CharField(default='just checking', max_length=200),
        ),
    ]
